### ISSUE TITLE
bug in institution search for substring words

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#104]
When searching for an organisation in geteduroam, the search stops when a space is involved... 

Search for "John" and you get 4 universities, one from Hungary, 3 from the UK. Use "John " (trailing space), and all UK ones go away, despite them all having "John " in their names ("John Moores", "St John "). Continue to type to "John m" (for "John Moores") and no university is left.

**Comment by p80-mike** [comment]
Tested on:
- iPhone XR, iOS 17.6.1

Version:
- geteduroam: 3.5.4 (1524)

**Test Approved**

Tested by performing the steps described in the description.
