### ISSUE TITLE
Support opening EAP config files from Files.app

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#115]

**Comment by johankool** [comment]
Test instructions:
- save config file in Files.app
- open the config file from there by long press -> Share -> geteduroam

**Comment by RianneBoortman** [comment]
Tested on:

iPhone 12 Pro Max, iOS 18.1.1
Version:
geteduroam nr 165
✅ test approved
If I share the .eap-config file and open it in geteduroam, without any issues
