### ISSUE TITLE
Languages in discovery json v2

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#117]

**Comment by johankool** [comment]
Discovery uses `{}` when profiles have no name instead of expected `[]`.

**Comment by johankool** [comment]
@jornane Can you fix the json?

**Comment by jornane** [comment]
Fixed, the issue was entirely in the [discovery generator](/geteduroam/cattenbak/), so no changes needed here.

**Comment by johankool** [comment]
Client side changes are needed and what this ticket was about.

**Comment by johankool** [comment]
![Image](https://github.com/user-attachments/assets/87ced617-2802-420d-a84a-39d9ea8ea0b1)
![Image](https://github.com/user-attachments/assets/462eddcd-3204-4930-ba50-ccf098b5779b)

**Comment by RianneBoortman** [comment]
Tested on: iPhone 11 Pro Max, iOS 16.7.2
Version: geteduroam v152

✅ test approved
I checked with the University of Ghent. This is a different name in NL than in ENG. Indeed, I can only see that one via searching on Ghent depending on the language that I am set in.
