### ISSUE TITLE
Avoid loading EAP config on macOS to prevent creating unnecessary accounts

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#118]
Don't show helpdesk info for now.

**Comment by johankool** [comment]
Test instructions: verify in Charles Proxy or Proxyman that no needless API calls are mode to fetch organization/helpdesk info

**Comment by RianneBoortman** [comment]
Tested on:
- MacBook Pro, MacOS 15.1.1
Version:
- Geteduroam nr 165

✅ test approved
I connected my device to Charles Proxy. I searched and added Tilburg University and Uninett. With both of them I do not see strange things happening in my proxy. So it seems to me that no unnecessary calls are being made.
