### ISSUE TITLE
Provide feedback to users not entering their realm properly

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#121]
The realm input in the username is properly enforced in the iOS App (as well as an explicit match @realm.tld or otherwise (*.)realm.tld) but no user feedback is visible (it's maybe provided for a very short time).

When this can't be made visible in the dialog (as we do on Andriod), perhaps show it in a popup of some sorts?

**Comment by johankool** [comment]
Test instructions: 
- go to "Eduroam Visitor Access (NL)"
- type "hello@example.com"
- type any password
- press Log In
- now a dialog shows

**Comment by p80-mike** [comment]
Tested on:
- iPhone XR, iOS 17.6.1

Version:
- geteduroam: 2.4 (128)

Test approved.
Provided steps used for testing.

![Image](https://github.com/user-attachments/assets/ac4c9531-f93c-40d2-b0b0-c1351836ca02)
