### ISSUE TITLE
Localizations for Estonian (et), Galician (gl) and Scottish Gaelic (gd) are missing

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#141]
Android has them

**Comment by johankool** [comment]
Estonian translation currently not available.

**Comment by RianneBoortman** [comment]
Tested on: iPhone 11 Pro Max, iOS 16.7.2
Version: geteduroam v152

✅ test approved
I now see that the GL and GD language is part of the app. I see the text being updated when I change the language in my phone
