### ISSUE TITLE
Make disabled state of Connect button more clearly disabled

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#25]

**Comment by RianneBoortman** [comment]
Tested on:
- iPhone 12 Pro Max, iOS 17
Version:
- geteduroam Test versie 2.0(62)

💹 test approved
See attached screenshot. Disable button looks more really disabled


![Image](https://github.com/geteduroam/apple-app/assets/50241594/63016502-9ef9-4a8e-a3a4-d6cec236cc5b)
