### ISSUE TITLE
Localize texts

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#27]
- [x] English
- [x] Catalan
- [x] Dutch
- [x] English (UK)
- [x] French
- [x] German
- [x] Hungarian
- [x] Italian
- [x] Polish
- [x] Portugese
- [x] Spanish
- [x] Welsh

**Comment by pauldekkers** [comment]
We have a number of translations for the old App; we can ask the community to provide them!

**Comment by RianneBoortman** [comment]
Tested on:
- iPhone 11 Pro Max, iOS 16.7
Version:
- geteduroam version 2.0.1 (60)
- getgovroam version 2.0.1 (38)

✅ test approved
I see that I can set the apps in the languages set above. When I select the other language, I see that the app is updated
