### ISSUE TITLE
Add way to inform users a recommended or forced update is available

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#32]
Do we want this? The idea is to add information about the latest versions to the discovery json so we can inform the user that they need to update. Alternatively we can also just rely on the update process of the App Stores, though then you can never 'kill' any versions of the app that may have issues.

**Comment by johankool** [comment]
Assigning @pauldekkers and @jornane as well to make decision on this feature.

**Comment by johankool** [comment]
I've created https://github.com/egeniq/app-remote-config which would work well for this project too. 

It works by hosting a json file that can be used to inform users about updates, or remotely configure other feature flags as desired.

**Comment by johankool** [comment]
Test instructions:
- put "geheim" in the pasteboard
- tap 10 times on the main screen
- tap and hold on the search icon
- choose "App Configuration…" from the menu
- choose other App Store and/or Maintenance mode

**Comment by RianneBoortman** [comment]
Tested on: iPhone 11 Pro Max, iOS 16.7.2
Version: Geteduid nr 163

✅ iOS app approved
We have the option now to do an update message. The user cannot do anything in the app when this message is shown.

MacOS version still needs to be checked
