### ISSUE TITLE
On macOS a subsequent navigation fails

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#33]
**Steps to reproduce:**

1. Search for "eva"
2. Tap first result
3. Go back
4. Tap second result

**Actual behavior:**

Nothing happens

**Expected behavior:**

Open second result

**Comment by johankool** [comment]
Proper fix here: https://github.com/pointfreeco/swift-composable-architecture/issues/2182

**Comment by RianneBoortman** [comment]
Tested on:
- MacBook Pro (2018), MacOS 13.4.1
Version:
- TestFlight geteduroam Test #2.0(47)

✅ test approved
I now see the expected behaviour happening. When I go back, and tap on that first item again, that section is opened and I see the profile is downloaded again
