### ISSUE TITLE
Use status indicator for network connection instead of error alert

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#39]

**Comment by RianneBoortman** [comment]
Tested on:
- iPhone 12 Pro Max, iOS 17
Version:
- 2.0, build 70

✅ test approved
See attached screenshot. I now get a message when the connection failed


![Image](https://github.com/geteduroam/apple-app/assets/50241594/0209f3da-d7e7-46e0-875d-a320acdced41)
