### ISSUE TITLE
Apps generate 2 new eap profiles

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#53]
During the configuration, the .eap-config is retrieved twice; this generates duplicate profiles (of which only one is used, the other one discarded on the client). It's fine to download the config to show some data/terms, but for actual configuration the same config should be used and not a new one.

On macOS this is probably more difficult, because not all information is available in .mobileconfig files, while on iOS the .eap-config is exactly the same.

**Comment by johankool** [comment]
Fixed for iOS with https://github.com/geteduroam/apple-app/pull/11

**Comment by RianneBoortman** [comment]
Tested on:
- MacOS
- iPhone 12 Pro Max
Version:
- 2.0, build 73

✅ test approved
I connected my Mac and iPhone to a proxy. I see only 1 api call coming by now
