### ISSUE TITLE
iOS uses old credential despite new one being generated

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#54]
While testing with a new configuration (previously eVA, new Moreelsepark) I noticed an old certificate was reused from end of May, instead of the new one(s) generated.

**Comment by pauldekkers** [comment]
Ahh, well I checked the RADIUS logs. I'm not sure if it is also visible in some debug output.

If you want, I can look up requests that you initiated from a client, or maybe we need to think of a way to make this visible to you. Maybe it's actually in the AP logging or visible in the admin screens: I'd need to check.

**Comment by johankool** [comment]
Moving to QA Client as this is difficult to test without a proper router setup.
