### ISSUE TITLE
Make icon stand out more

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#55]

**Comment by RianneBoortman** [comment]
Tested on:
- MacOS
- iPhone 12 Pro max
Version:
- 2.0, build 73

✅ test approved
See attached screenshot. The background now has a pinkish color. Then the blue stands out more


![Image](https://github.com/geteduroam/apple-app/assets/50241594/e96dfa05-dd6f-471c-85e9-1deb24fb6910)
