### ISSUE TITLE
Discovery json in v2 format for getgovroam

### ISSUE THREAD

**Issue by johankool** [geteduroam/apple-app#62]
We need a version of the discovery.json file for getgovroam that uses the v2 format.

**Comment by johankool** [comment]
Testable by seeing different content in getgovroam vs. geteduroam.

**Comment by RianneBoortman** [comment]
Tested via:
- iPhone 12 Pro Max, iOS 17.1.1
- MacBook Pro 2018, macOS 14.1.1
Version:
- iPhone: geteduroam 2.0 (42)
- iPhone: getgovroam 2.0(19) 
- macOS: geteduroam Test 2.0 (93)
- macOS: getgovroam Test 2.0 (85)

✅ test approved
I see that there is a difference in the content. When I search on "test", I get different results
