### ISSUE TITLE
Arabic username & password prompts are both left-to-right

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#85]
Received an answer from the Arabic translation team: username and password input should both be left-to-right

**Comment by johankool** [comment]
<!-- Uploading "Simulator Screenshot - iPhone 15 Pro - 2024-01-25 at 09.28.51.png"... →

**Comment by johankool** [comment]
![Image](https://github.com/geteduroam/apple-app/assets/68731/dc68bfaf-f132-48af-b34c-0de30b9d9c9b)

**Comment by RianneBoortman** [comment]
Tested on:
- iPhone 11 Pro Max, iOS 16.7
Version:
- geteduroam version 2.1 (83)
✅ test approved
I see the same as the screenshot of Johan above. The login is now from right to left
