### ISSUE TITLE
updating iOS geteduroam.app to v2.0.2 requires users re-install profile, existing profiles should remain intact across versions of app

### ISSUE THREAD

**Issue by teamktown** [geteduroam/apple-app#86]
As of Jan 10, v2.0.2 we are hearing of some iOS devices not persisting their profile once the app is updated on iOS.

**Workaround:**
 We advise people if they encounter the problem to refresh installing their profile.  

**Expected behaviour:**
Users expect existing profiles to survive geteduroam.app version updates and desire the geteduroam.app to gracefully handle the existence of eduroam profiles.

It is unclear if the actual eduroam profile on iOS is persistent in the app itself  and if the [Managing data Across App updates](https://developer.apple.com/library/archive/technotes/tn2285/_index.html#//apple_ref/doc/uid/DTS40011323-CH1-FILES) is a practice employed by the geteduroam.app for wifi profiles.

**Recommendation:**
Users should:
-  be able to freely update their eduroam app without triggering profile problems
-  when updated have some way to know what version they are at (may already exist)
-  if a profile is active or in use (optional, if possible given security sandboxes etc)

**Comment by johankool** [comment]
Thanks for the feedback. Do you know if these users updated from 2.0.0 (the first release) of this app, or from the previous 1.x version?

The profile lives in the system and the keychain. It is not something that the app saves to disk, so the linked persistence docs shouldn't apply.

**Comment by spaetow** [comment]
I think we need to assume that it's from v1.x to v2.0.2 since that's the newest version.

**Comment by teamktown** [comment]
as far as we know it was from pre 2.x to 'latest 2.x'.  Fair statement on the persistent docs, my recommendations stand as we progress forward so we can managed user expectations (code+docs+website info) and the desired duty of care people expect of the geteduroam.app.

Recommendations still are:
- be able to freely update their eduroam app without triggering profile problems
- when updated have some way to know what version they are at (may already exist)
- if a profile is active or in use (optional, if possible given security sandboxes etc)

welcome feedback on this

**Comment by zmousm** [comment]
In my experience the pseudo-credentials were installed with app version 1.x on iOS 16.x; everything worked and the app was not used again. The device was afterwards gradually updated to iOS 17.1.2. The device was recently (2024-01-11) brought to a known and previously used hotspot and then I realized that:
* it did not recognize the eduroam SSID, despite having previously connected to the particular BSSID
* upon manually selecting the SSID, the device presented the default prompt for credentials
* configuration profile(s) for eduroam no longer showed up under settings (not sure if they should anymore)
* the geteduroam app had been automatically updated to version 2.0.2 in the previous days (on 2024-01-09)
