### ISSUE TITLE
make Passphrase optional in .eap-config

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#87]
The current version requires the `<Passphrase>` to be present in the .eap-config, in the `<ClientSideCredential>`. This is the case in the portal provided `.eap-config` files, but there are profiles without the Passphrase. While that's mostly used for Android, I think it's a good idea to prompt the user for a Passphrase if the element is missing, eg. with "This profile requires a passphrase" (that would be a new translatable string.)

**Comment by RianneBoortman** [comment]
Not something that I can test. Can you see if this is ok now Paul?
