### ISSUE TITLE
support loading of outside of App downloaded .eap-config profiles

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#88]
Currently .eap-config files are only loaded from in-App workflow; we'd like to support the installation of files downloaded with the .eap-config extension outside of the App. (If there is no user input required, eg. u/p or passphrase, it's a good idea to ask for confirmation first.)

**Comment by johankool** [comment]
Short tap on search icon now puts focus on the search field for typing
Long tap on search icon shows menu with "Open File…" option to select EAP Config file on device.

**Comment by RianneBoortman** [comment]
Tested on:
- iPhone 12 Pro Max, iOS 18.1.1
Version:
- geteduroam nr 165

✅ test approved
I can load a .eap-config file without any issues.
