### ISSUE TITLE
internal TestFlight 2.1 (83) display an error

### ISSUE THREAD

**Issue by pauldekkers** [geteduroam/apple-app#94]
Configuration doesn't work for geteduroam TF 2.1 (83) and getgovroam TF 2.1 (61), the error displayed is:

<img src="https://github.com/geteduroam/apple-app/assets/5858113/2aecf3ad-1794-49bb-bc48-10034a26f1cd" width="350">
<img src="https://github.com/geteduroam/apple-app/assets/5858113/a98a1014-90f9-4ff5-aeac-f77bc33a608d" width="350">

**Comment by johankool** [comment]
Caused by fix for #75
